### PR TITLE
Added support for different page formats (A4, letter, custom) and cleaned up/fixed code.

### PR DESCRIPTION
**Pull request by regexident**
Solve #5.

See commit messages.

### CODE REVIEW

**Comment by as-cii** [comment]
The code has changed significantly since you opened this PR. I am truly sorry for that, as this needs to be closed, but you did a great job here, really! :clap: 

@regexident: would you be interested in bringing this library forward? As stated in #24, I have very little time to maintain this and I am searching for someone who can give the time this project deserves. You won't be alone in the journey, as I'll provide guidance and assist you throughout the whole redesign process.

Please, leave a comment in #24 if you're interested. Thanks :bow:

**Comment by regexident** [comment]
[DLPDFRenderer](https://github.com/regexident/DLPDFRenderer) :wink:

**Comment by as-cii** [comment]
@regexident: no problem. Thank you anyway for taking the time to contribute.

Unfortunately I don't see DLPDFRenderer as a substitute for this library, given that PdfReportKit addresses templating too. However, it may be interesting to remove all Pdf generation code from here and use your library instead.

Thank you!

**Comment by regexident** [comment]
That's actually what DLPDFRenderer was intended for.  
To allow you to use it as a rendering backend for higher-level PDF generation libraries/applications.

**Pull request closed without merging**
